### ISSUE TITLE
IDE Driver

### ISSUE THREAD

**Issue by gdx-msx** [Konamiman/Nextor#104]
I noticed in the sunride.asm file that mulub a,a is used although this instruction is deprecated by ASCII.

```
	; Check for a Z80 or R800
	xor	a		; Clear Cy
	dec	a		; A=#FF
	db	#ED,#F9		; mulub a,a
	jr	c,.useLDIR	; Always use LDIR in RAM for the R800`
```

**Comment by grauw** [comment]
Despite what documentation says, afaik MULUB actually works fine on all registers.

MULUW is restricted to just HL,BC and HL,SP.
