### ISSUE TITLE
Files with "file system" attribute, can't be opened with "open filehande"

### ISSUE THREAD

**Issue by bladeba** [Konamiman/Nextor#11]
when you "open filehandle" in a file with "file system" attribute, the "filehandle" won't be opened correctly and NO error is returned.

**Comment by Konamiman** [comment]
Could you please specify what "won't be opened correctly" exactly means? No proper file handle returned? Errors when trying to read the file? Something else?

**Comment by bladeba** [comment]
Devuelve error y no lee del FCB. .. Como si intentara escribir en vez de
leer

**Comment by Konamiman** [comment]
Please post some example code that reproduces the bug (and write your comments in English) :-)

**Comment by Konamiman** [comment]
Fixed in v2.1.0 beta 2
