### ISSUE TITLE
Sunrise IDE emulators ROM file name

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#112]
I just tested the openMSX v17.0 IDE interface, and it works just fine with the [Nextor-2.1.1.SunriseIDE.ROM](https://github.com/Konamiman/Nextor/releases/tag/v2.1.1) .

So please rename the Nextor-2.1.1.SunriseIDE*.emulators.ROM files to Nextor-2.1.1.SunriseIDE*.blueMSX.ROM, because that's the emulator that doesn't support the new IDE driver.  Otherwise the file name will mislead users to use the incorrect/slower ROM with openMSX.

**Comment by ATroubleshooter** [comment]
I do confirm, 2.1.1 works for "ages" without an issue with OpenMSX 17.
edit: driver v0.1.7.

**Comment by Konamiman** [comment]
That makes sense, and it will be fixed: https://github.com/Konamiman/Nextor/pull/129
