### ISSUE TITLE
DSK/EMU file doesn't start properly.

### ISSUE THREAD

**Issue by tspoor** [Konamiman/Nextor#120]
Using:
Panasonic_FS-A1GT
MegaFlashRom SCC+ SD

Nextor Kernel Version 2.1.2 alpha 1
NEXTOR.SYS version 2.12
COMMAND2.COM version 2.44
EMUFILE v1.21
Dutch MoonSound Veterans Disk 1

Steps to reproduce:
1. CD MB¥DMV 
2. EMUFILE DMV.EMU DMV1.DSK
3. 1 disk image registered.
4. EMUFILE SET DMV.EMU
5. Done. Resetting computer  (System reboots)
6. It seems to start AUTOEXEC.BAS, however the screen remains black and system hangs.

The following works:
1. MAPDRV G: DMV1.DSK
2. G:
3. BASIC AUTOEXEC.BAS

And loading it in the cartridge works:
1. OPFXSD DMV1.DSK /D1
2. Press reset button

**Comment by Konamiman** [comment]
Hi, this is not actually a bug in the disk emulation feature: the DMV will fail too when booting Nextor in MSX-DOS 1 mode, even when not in emulation mode.

Strictly speaking this is a bug in the DMV (wrong detection of the MSX-DOS version), not in Nextor. But anyway I'll make a small change in Nextor that will make this issue disappear. Details in https://github.com/Konamiman/Nextor/pull/128.

**Comment by tspoor** [comment]
Sorry forgot to provide my feedback. All is good now and it works as expected. Thank you!
