### ISSUE TITLE
Suggestion: Pass the status of the CTRL and SHIFT keys to the driver DRV_CONFIG and DRV_INIT

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#16]
The diskROM reads the status of the CTRL and SHIFT keys at the moment it issues a BEEP in the boot sequence.

Please pass the status that the CTRL and SHIFT keys had at the moment of the boot beep to the driver DRV_CONFIG and DRV_INIT functions, so the driver can take decisions accordingly, like adjusting DEV/LUNs, reduce the allocated workRAM, etc.

**Comment by Konamiman** [comment]
Implemented partially in v2.1.0 beta 1. DRV_INIT and DRV_CONFIG (when asked for the number of drives to allocate) get the status of the 5 key passed, this is the key to request one single drive per driver in Nextor 2.1.
