### ISSUE TITLE
Nextor ROM should boot MSXDOS2.SYS when NEXTOR.SYS isn't found

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#17]
For backward compatibility reasons, the Nextor ROM should boot the MSXDOS2.SYS file when the NEXTOR.SYS file isn't found.

Only this way it's possible to use a standalone Nextor cartridge to fully replace a MSX-DOS2 standalone cartridge, for example. Otherwise disk games based on the MSX-DOS2 won't boot.

**Comment by Konamiman** [comment]
Implemented in v2.1.0 beta 2
