### ISSUE TITLE
Partitions created by FDISK mustn't be the same name

### ISSUE THREAD

**Issue by plainspooky** [Konamiman/Nextor#2]
All partitions created by FDISK tool there are the same name "NEXTOR 2.0 " (source/kernel/bank5/fdisk2.c) and it is a bit confuse to identify each one on UNIX like operating systems.

**Comment by plainspooky** [comment]
I've opened this just for keep it in mind. It's a simple improvement but I need to build Nextor on Linux first :-)

**Comment by Konamiman** [comment]
Thanks for the suggestion, but what you call the "partition name" is actually the OEM name (https://en.wikipedia.org/wiki/Design_of_the_FAT_file_system) and identifies the system that created the filesystem. Are you sure that *-IX OSes use this value for partition identification?
