### ISSUE TITLE
Nextor incorrectly identifies certain keys on MSXs with different keyboard layout

### ISSUE THREAD

**Issue by Wierzbowsky** [Konamiman/Nextor#22]
Here's my bug report, it affects earlier Nextor (Alpha), also probably applicable to the Beta. On KYBT and KYBT2 systems (Russian versions of YIS503II and YIS503III) the keyboard behaves differently than on other machines - the number keys are somehow shifted to the right. For example if you press '9' at Nextor's bootup screen, it acts as if '0' is pressed on other machines to stop using the previously assigned bootable image. This makes switching disk images and ignoring booting of the assigned DSK image a bit difficult.

On the Russian Yamaha YIS805 the numeric keys above the alphabetic ones don't work at all, so the only way out is to use the numeric keys on the side of the keyboard (numeric keypad).

I presume Nextor is using scancodes to identify the keys. It appears that on some machines there will be a discrepancy between what the scancode is supposed to get and what the key actually means. This is true for non-QWERTY keyboards like in those on Russian Yamahas. So not only the numbers, but letters could be also affected.

**Comment by Konamiman** [comment]
Support for Russian keyboards added in v2.1.0 beta 2
