### ISSUE TITLE
Nextor Beta1 doesn't work on Carnivore2 - no longer booting to MSX-DOS2

### ISSUE THREAD

**Issue by Wierzbowsky** [Konamiman/Nextor#23]
Just tried Nextor Beta1 on my Carnivore2 cartridge. Flashed the "Nextor-2.1.0-beta1.SunriseIDE.ROM" file into the cartridge as BIDECMFC.BIN, copied the "Nextor.sys" and the tools into the root folder of the CF card and rebooted. 

As a result the cartridge is no longer able to boot to MSX-DOS2. The system just hangs after Nextor's copyright message is shown. Sometimes the background color becomes the same as the border color on my MSX2+ before the system hangs.

The test was done on diskless Yamaha YIS503III upgraded to MSX2+.

**Comment by Konamiman** [comment]
Please test if you are able to boot:

1. Directly to BASIC (press 3 while booting)

2. In MSX-DOS 1 command prompt (copy MSXDOS.SYS and COMMAND.COM to the device, then press 1 while booting)

**Comment by Wierzbowsky** [comment]
I will test this once the bug with non-booting on diskless computers is fixed. Because after flashing the current BIOS I can no longer use the Carnivire2 cartridge to boot to MSX-DOS2.

**Comment by Wierzbowsky** [comment]
1. Booting to Basic with '3' works.
2. Booting to MSXDOS1 with '1' does not work.
3. Booting to MSXDOS2 only works if there's another drive in a system (for example Gotek adapter in side slot), without the drive I can see Nextor's messages, then screen goes blank, but command prompt does not appear. This problem is reported by several people.

Currently I am running lots of iterations of IDE testing tool with Nextor Beta1 to see if there are any write/read errors.

**Comment by Konamiman** [comment]
Can you please try this? Get a regular MSXDOS2.SYS file, rename it to NEXTOR.SYS and try to boot with it. This way I'll know if the problem is in the kernel or in NEXTOR.SYS.

**Comment by Wierzbowsky** [comment]
Renamed MSXDOS2 into NEXTOR.SYS - same issue. If another disk drive is present, system boots, otherwise just hangs. The problem seems to be in kernel.
