### ISSUE TITLE
The name of the DSK emulation configuration file should be changed

### ISSUE THREAD

**Issue by Wierzbowsky** [Konamiman/Nextor#25]
The name of the emulation settings file NEXT_DSK.DAT should be changed to avoid accidental deletion of NEXTOR.SYS file after disabling the emulated DSK image and booting back to MSX-DOS2. When typing "del next" and pressing TAB the first 2 files to be found may be NEXTOR.SYS and NEXTORJP.SYS.

The name of the DSK emulation settings file should not contain any sequence of letters that Nextor's files have. It should be something pretty simple, unique, and easily visible, for example "`_DSKEMU_.CFG`" or just "`DSKEMU.CFG`".

**Comment by Konamiman** [comment]
"Fixed" (new emulation modes introduced) in v2.1.0 beta 2.
