### ISSUE TITLE
Proposal for alternative image changing trigger

### ISSUE THREAD

**Issue by Wierzbowsky** [Konamiman/Nextor#26]
According to the documentation an alternative way to change the mounted DSK image is: "Alternatively, you can also press the GRAPH key when the computer is trying to read the file. The caps led will lit and the computer will freeze until you release GRAPH and press the appropriate file key."

I believe it would be better to detect the GRAPH key being pressed for more than 3 seconds to enable the disk changing mode because catching the file's access while pressing GRAPH may not be an easy task in all situations. In the disk changing mode if GRAPH is pressed again, the mode should be deactivated (in case a user changed his mind).

**Comment by Konamiman** [comment]
Implemented (sort of) in v2.1.0 beta 2: now you can press GRAPH while Nextor is waiting for the new disk key to cancel the disk change.
