### ISSUE TITLE
Implementing phantom floppy drive in device-based subsystem

### ISSUE THREAD

**Issue by Eugeny1** [Konamiman/Nextor#42]
As I understood from conversation with Nestor that phantom drive and "Insert the diskette form drive X:" must be implemented in driver for device-based configuration. If DEV_STATUS will be called as polling then it will cause driver to display unexpected "Insert the diskette" messages if DEV_STATUS is called for phantom driver and back.
Thus I need confirmation that DEV_STATUS is called only when kernel wants to perform I/O access of specific logical drive.
In general the message "Insert diskette" and related routines are present in both DOS1 and DOS2 kernels of Nextor, and it would be logical to reuse them in device-based configuration.

**Comment by Konamiman** [comment]
Final version of Nextor 2.1.0 will provide a proper PROMPT routine for this purpose.

**Comment by Konamiman** [comment]
Fixed in v2.1.0 (PROMPT routine made visible, and "ignore when auto-assigning" flag in LUN_INFO)
