### ISSUE TITLE
Nextor shouldn't block sector I/O to MAPDRV drives when FAT12 disk images are used

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#43]
Nowadays, Nextor blocks sector I/O to FAT16 partitions, as a safety measure.
But, weirdly enough, it's also blocking sector I/O to MAPDRV drives of FAT12 disk images. This causes DOS2 programs that rely on sector I/O to fail.

For example: These are the results when you try to run the demo of the game F-Nano2' on Nextor 2.1.0RC1:

- Copy the files to a folder on a FAT12 partition: Runs fine
- Copy the files to a folder on a FAT16 partition: Fails because sector I/O is blocked
- Use EMUFILE: fails because the game requires DiskBIOS2
- Use MAPDRV: fails because sector I/O is blocked

You can download the demo of F-Nano2' [here](https://www.msxgamesworld.com/gamecard.php?id=3919).

**Comment by Konamiman** [comment]
Hello, thanks for your report. Just to be sure:

* By "blocks sector I/O" what do you mean exactly? The RDABS function call maybe? 
* By "MAPDRV drives of disk images" do you mean mounting a disk image file in a drive?
* How does it fail exactly?

**Comment by sdsnatcher** [comment]
> By "blocks sector I/O" what do you mean exactly? The RDABS function call maybe?

Yes, when I opened the ticket I had _RDABS (2Fh) and _WRABS (30h) BDOS functions in mind.

I'm not sure if PHYDIO is also affected.

> By "MAPDRV drives of disk images" do you mean mounting a disk image file in a drive?

Exactly. To be able to play DOS2 disk games, i.e.

> How does it fail exactly?

I don't remember the details now, but IIRC, RDABS/WRABS just returned an error code (A>0) without doing anything else.

**Comment by Konamiman** [comment]
Hi, this is a bug, the RDABS/WRABS and RDDRV/WRDRV calls are supposed to work fine on drives with mounted files. Thanks for reporting.

**Comment by Konamiman** [comment]
Fixed in v2.1.0
