### ISSUE TITLE
DRV_CONFIG is called 2 times when going to be in DOS1 mode

### ISSUE THREAD

**Issue by Eugeny1** [Konamiman/Nextor#44]
If pressing and holding "1" key (boot into DOS1 mode) this routine, DRV_CONFIG, is first called in DOS2 mode (B=0), with A=1 and then with A=2 (with call count equal to number of drives requested). If, during first call (when input A=1) driver returns no error, kernel calls DRV_CONFIG again with A=1, but now in DOS1 mode (B=1), and performs another round of query of devices/LUNs. This problem will not be noticed by the drivers not supporting DRV_CONFIG or boot-time drives.
If driver displays messages (e.g. configuration summary) then the message will appear twice.
If driver must perform configuration only once after the hardware initialization (DRV_INIT), it will be confused by the second call.

**Comment by Konamiman** [comment]
DRV_CONFIG is a routine intended exclusively to return information, it should not perform any other action as there's no way to know how many times it will be called. Initialization messages should be printed only on DRV_INIT.

**Comment by Eugeny1** [comment]
Storage microcontroller must know the DOS mode it is going to be used in at its hardware initialization stage - as it will be using different configuration profiles for DOS1 and DOS2 modes.
