### ISSUE TITLE
DRV_CONFIG behavior when it returns A=1 for function A=1

### ISSUE THREAD

**Issue by Eugeny1** [Konamiman/Nextor#47]
The driver template states:

;-----------------------------------------------------------------------------
;
; Get driver configuration 
; (bit 2 of driver flags must be set if this routine is implemented)
;
; Input:
;   A = Configuration index
;   BC, DE, HL = Depends on the configuration
;
; Output:
;   A = 0: Ok
;       1: Configuration not available for the supplied index
;   BC, DE, HL = Depends on the configuration
;
; * Get number of drives at boot time (for device-based drivers only):
;   Input:
;     A = 1
;     B = 0 for DOS 2 mode, 1 for DOS 1 mode
;     C: bit 5 set if user is requesting reduced drive count
;        (by pressing the 5 key)
;   Output:
;     B = number of drives
;
; * Get default configuration for drive
;   Input:
;     A = 2
;     B = 0 for DOS 2 mode, 1 for DOS 1 mode
;     C = Relative drive number at boot time
;   Output:
;     B = Device index
;     C = LUN index

DRV_CONFIG:

If driver, for configuration index A=1 returns A=1 ("Configuration not available for the supplied index"), kernel assumes that driver wants 2 drives and calls DRV_CONFIG with index A=2 two times for relative drive numbers 0 and 1.
I believe if driver returns error for call with A=1 kernel must assume there will be no drives at all.

If driver returns A=0 and B=0 for the first call, then kernel properly behaves as there are no dirves.

**Comment by Konamiman** [comment]
This behavior is on purpose. When the driver returns "configuration not available" when invoking DRV_CONFIG, the behavior is always "use the default Nextor behavior". For the case of the number of drives at boot time the default Nextor behavior is to map two drives per driver, and that's exactly what you are seeing.
