### ISSUE TITLE
MAPDRV "Invalid drive" error if do not supply parameters after the partition number

### ISSUE THREAD

**Issue by mr-GreyWolf** [Konamiman/Nextor#48]
I get an error **Invalid drive** if I do not explicitly indicate the device index and driver slot/subslot
`mapdrv c: 2`

this command work fine:
`mapdrv c: 2 1 2-1`

Tested on Carnivore2 / Nextor 2.1.0-beta2

**Comment by Konamiman** [comment]
Hi, the short verion of `mapdrv` (specifying only drive and partition number) works only if the drive is already mapped to another partition on the same device, if not you need to specify also device number (and also controller slot if the driver wasn't already assigned to a device on that controller). How was the existing mapping of the drive you were trying to map?

**Comment by mr-GreyWolf** [comment]
This is first mapping for this device.

**Comment by Konamiman** [comment]
I mean the previous mapping of drive C:, if that drive wasn't already mapped to that device then indeed you need to use the long version of the command.
