### ISSUE TITLE
DEV_BASSTAT and register changed

### ISSUE THREAD

**Issue by Eugeny1** [Konamiman/Nextor#50]
Documentation must explicitly state that code in DEV_BASSTAT must not change HL register, If HL is changed then the _SYSTEM gives Syntax error if HL happens not to point to byte with value of 0.

**Comment by Konamiman** [comment]
The documentation says that the tools to implement CALL commands in a Nextor kernel are the same ones used in regular ROMs (the routines in the MSX-BASIC ROM), and the description for these routines in MSX2 Technical Handbook already state that HL contains the pointer to the BASIC text for both the input and the output of these routines.

However, the documentation points only to [chapter 2](https://github.com/Konamiman/MSX2-Technical-Handbook/blob/master/md/Chapter2.md) of MSX2 Technical Handbook (BASIC) and it should also point to [chapter 5](https://github.com/Konamiman/MSX2-Technical-Handbook/blob/master/md/Chapter5b.md) (slots and cartridges), so I'll change that.
