### ISSUE TITLE
_FDISK: partitions can not be added

### ISSUE THREAD

**Issue by Eugeny1** [Konamiman/Nextor#51]
I created one 4096M partition on the 149 GB disk, saved changes. Used the partition for some time, and then decided to add another partition. But there's no option to add another partition, the only way to create new partition is to delete all the partitions, and then recreate everything from scratch -> data loss.
Why it is not possible to add partitions into the free space after initial configuration is created? Is it possible to change this?

**Comment by Konamiman** [comment]
The built-in FDISK is a basic tool intended to allow you to get started with a device that is not properly partitioned. Altering existing partitions is advanced functionality and if you need it you should use a more advanced tool (possibly a non-MSX one).

Additionally, FDISK is taking a ton of space in the kernel ROM (32K) and in future versions I plan to make it even simpler to make room for new code for other features.
