### ISSUE TITLE
Impossible to implement phantom drive properly

### ISSUE THREAD

**Issue by Eugeny1** [Konamiman/Nextor#54]
The problem starts just at the system start: after DRV_CONFIG is finished, kernel tries to identify the contents of the media in the drives reading boot sectors, however as there's only one diskette drive and another one is phantom, this action causes messages

![DSCN2265-1](https://user-images.githubusercontent.com/12286988/81236658-5c3e1f00-9006-11ea-938a-a78547f75f5c.JPG)

as kernel has no idea that these drive letters are the same physical drive. It is not possible to overcome at the driver level, and requires changes in the kernel.

Second issue, where to obtain current the letter of the current device to display the prompt: YF33F seems to contain invalid information when device enumeration is being performed (see prompt strings above - for all the devices enumerated YF33F has value of 0). However it seems to contain correct drive letter reference when booting is started.

Third issue, at some point in time (when booting is attempted) the PROMPT hook XF24F is set with jump to somewhere, and machine crashes. When device enumeration is performed before this event, the hook properly contains the RET.

![DSCN2271-1](https://user-images.githubusercontent.com/12286988/81236700-74ae3980-9006-11ea-8f24-5a34ef61a41a.JPG)

On the pictures -Dx means calling the prompt checking routine for the device x. If prompt is going to be displayed, routine also displays contents of 3 bytes starting XF24F. The first pictures show C9C9C9, while second at the top shows jump to some address EAC6. The jump to this EAC6 ends at some Nextor kernel location displaying arbitrary strings from built-in FDISK application.

Also you can see as soon as booting process started and DOS2 is loaded, YF33F contains correct reference to device current number (as it starts displaying A: and B: in the prompt).

**Comment by Eugeny1** [comment]
The solution to this problem is setting up two flags in the LUN_INFO:

- phantom device flag;
- not bootable device flag.

It is generally possible to merge these two flags into the one flag (phantom/non-bootable) if Nextor is not going to implement phantom drives and will leave this task to the driver. If driver sets this flag, device is not attempted to be booted from.

**Comment by Konamiman** [comment]
Final version of Nextor 2.1.0 will provide:

- A callable PROMPT routine.
- A new flag returned by LUN_INFO that means "skip device when searching for candidate drives for automapping"

Those two should allow to implement the functionality that you mention.

**Comment by Eugeny1** [comment]
Unfortunately this did not solve the problem of the "insert diskette" at the startup. Driver, in its DEV_STAT routine, still asks to insert phantom disk into logical drive to get its status because kernel asks for the status of the phantom drive/LUN.
Is it possible to exclude phantom drive from the status querying at the startup?

**Comment by Konamiman** [comment]
Please look at how the Rookie Drive FDD does it: https://github.com/Konamiman/RookieDrive-FDD-ROM/blob/master/msx/bank1/misc.asm#L128 - that `CHECK_SAME_DRIVE` routine is executed both when performing sector read/writes and when checking for disk change status.

Basically:

* You need to keep a variable (in page 3 work area for the driver, unless your hardware has its own RAM) holding the last drive number accessed (in your case I guess it would be the last device number accessed, and only when that device either has a phantom sibling or is a phantom itself). 
* Then in `DEV_STATUS` and `DEV_RW` you check the requested device and if it's not the same as the one stored, you invoke `PROMPT`. 
* At the end of these routines you update the variable, regarldess of whether you called PROMPT or not.

**Comment by Eugeny1** [comment]
The driver does exactly this you describe.
Let me explain the problem again.

Look at the very top picture of my original post. You can see machine says "-D1", then "-D2", then 3 hex codes and "insert diskette". "-Dx" is kernel invoking DEV_STATUS routine. Thus when kernel starts, it tries to obtain the status of the all devices, and calls DEV_STATUS several times. Of course, as soon as it calls DEV_STATUS for phantom device (-D2), driver sees that kernel selects another logical floppy drive (phantom one) and displays "insert diskette".

Now look further into the picture. Kernel obtains status of other devices (-D3, -D4 ... -D7), driver displays nothing because these devices do not exist or they have no phantoms.

Then kernel again tries to obtain status of primary drive (-D1), causing another "insert diskette" prompt because last drive accesses was drive 2 (phantom drive when querying its status).

Then again, kernel queries phantom drive for status "-D2" and driver displays another "insert diskette" message.

Now look at the second picture. Before booting. kernel again checks the status of the device 1 (primary floppy, "-D1"), but as it was querying status of phantom before, this causes another "insert diskette" message.

Thus there're in total 5 "insert diskette" messages appearing when Nextor kernel starts.
If kernel does not check status of phantom drives at its start (as obviously it will not be going to do anything with them at this stage), these messages would not appear.

I hope it is clearer now.

**Comment by Konamiman** [comment]
Implemented in v2.1.0 ("ignore when auto-assigning" flag in LUN_INFO)
