### ISSUE TITLE
In DOS1 mode files with certain extensions can't be found/loaded

### ISSUE THREAD

**Issue by Wierzbowsky** [Konamiman/Nextor#55]
When Nextor 2.1.0 Beta 2 is booted in MSX-DOS1 mode from the DSK image, files with certain characters in their extensions can not be found and loaded by the system. If the files are renamed with a different extension, the problem disappears.

The below ZIP archive contains the video showing the problem and the DSK image that Nextor boots from in DOS1 mode:

http://rbsc.su/files/nextor_bug.zip

The bug is shown on the video time 3:50. Files with '3' and '4' in their extensions can't be found.

**Comment by Konamiman** [comment]
Hi, long story short, this is due to a `db 34` in the code that handles illegal filename characters that was mistyped as `db "34"`. Thanks for reporting, it will be fixed in the next release of the Nextor kernel.

**Comment by grauw** [comment]
For the record, a user report [here](https://www.msx.org/forum/msx-talk/general-discussion/accessing-sd-data-on-megaflashrom-scc-sd-on-64kb-msx2?page=6).

**Comment by Konamiman** [comment]
Fixed in v2.1.0
