### ISSUE TITLE
_MAPDRV mount disk image - buffers from RAM on write not save to disk.

### ISSUE THREAD

**Issue by mr-GreyWolf** [Konamiman/Nextor#58]
Nextor kernel version 2.1.0 beta 2
NEXTOR.SYS version 2.10
COMMAND2.COM version 2.44

Buffers from RAM on write not save to disk.
Example:
1. I mapped floppy disk image(size: 737280 bytes) by commands:
```
_MAPDRV("B:","A:BASIC_PG\BASIC.DSK")
_CHDRV("B:")
```
2. I saved file from BASIC, file successful saved and viewed by by command `FILES`.
3. I reboot machine but file on disk image is not found...
I viewed this image on PC and found this file content, but file name in FAT table is missing.

**Comment by Konamiman** [comment]
Hello, I'be been able to reproduce not this exact bug but a similar one: after creating a file with `copy con` on a mounted file, the file gets apparently created, but then trying to display the file contents with `type` gives garbage. Clearly there's something wrong when writing to mounted files. Thanks for reporting!

**Comment by Konamiman** [comment]
Fixed in v2.1.0
