### ISSUE TITLE
DiskROM should only boot the partition marked as bootable, when more than one partition is present

### ISSUE THREAD

**Issue by sdsnatcher** [Konamiman/Nextor#6]
When there's more than one partition in the media, the Nextor diskROM shouldn't boot a partition that isn't marked as bootable. This could lead to problems if multiple operating systems are installed. (I.e.: Nextor and Uzix) There will be no way to use a boot loader like UZLO.

**Comment by Konamiman** [comment]
Implemented in v2.1.0 beta 2 (the first partition found with the "active" flag set is mounted at boot time)

**Comment by ATroubleshooter** [comment]
> Implemented in v2.1.0 beta 2 (the first partition found with the "active" flag set is mounted at boot time)

Excuse me, but is this the reason why another partitions on that same media are no longer getting drive letters assigned to them?
I believe that drive letters should be mapped to the valid non-hidden partitions, regardless of whether they are active or not. And boot only from the active one.

**Comment by ATroubleshooter** [comment]
Well, on MSX, probably, it is a generally expected behavior, and even the most preferable in total. I just don't know.

**Comment by Konamiman** [comment]
Related discussion: https://msx.org/forum/msx-talk/general-discussion/nextor-and-automatic-drive-mappings. The TLDR is that, at least in the short term, this behavior isn't going to change.

**Comment by ATroubleshooter** [comment]
> Related discussion: https://msx.org/forum/msx-talk/general-discussion/nextor-and-automatic-drive-mappings. The TLDR is that, at least in the short term, this behavior isn't going to change.

Allright, I've read this forum thread, and what I can say so far... well, may be one day in a future ;)

**Comment by ATroubleshooter** [comment]
Coz, as a newcomer(from linux), I'd say it wasn't at once that I learned to use MAPDRV. And if to speak about someone, who's just come from DOS&Windows-realm and is not used to fiddle with mounts so much, neither to RTFM in such amounts...  :)
