### ISSUE TITLE
National FS-4600F computer resets on IDE detection

### ISSUE THREAD

**Issue by Wierzbowsky** [Konamiman/Nextor#74]
Recently I've got the National FS-4600F MSX2 computer from Japan and tried my Carnivore2 with it. To my surprise I saw that the computer resets on IDE device detection with Nextor 0.1.7 driver. After reboot MSX-DOS2 loads normally. I could even reproduce this problem with OpenMSX, so this is not likely to be the Carnivore hardware's or firmware's fault. Please take a look, thanks.

**Comment by Konamiman** [comment]
Hi, can you still reproduce this issue with the latest version of Nextor? I can't, tried using blueMSX with the FD-4600 machine.

**Comment by Wierzbowsky** [comment]
Yep, still happens with the Nextor v2.1.1 Beta 2. But only on cold boot after you press ESC in the Boot Menu of Carnivore2 to exit. After the card detection prompt there comes a green screen and reset.

**Comment by Konamiman** [comment]
You say that you were able to reproduce it in OpenMSX. Could you please try with another non-IDE Nextor driver?

**Comment by Wierzbowsky** [comment]
Sorry, not sure what you mean by other non-IDE Nextor driver. MFR?

**Comment by Konamiman** [comment]
Yes, that could work, I meant any Nextor driver that is not the IDE driver (to rule out driver issues).

**Comment by Konamiman** [comment]
Could you please provide the exact configuration you used for testing with OpenMSX?

**Comment by Wierzbowsky** [comment]
OpenMSX v0.18.0 RC2. Original ROMs for the FS-4600F MSX, default Carnivore2 v2.52 files for OpenMSX from the repository:
https://github.com/RBSC/Carnivore2/tree/master/OpenMSX

After cold boot, press ESC in Boot Menu. After Nextor detects the CF card, the screen turns green and a machine reboots. After reboot, pressing ESC in Boot Meny doesn't result in a reset and DOS2 gets loaded successfully. The emulator behaves exactly the same way as the real machine.

At the moment of the crash the control is passed to BIOS's address 0 with some weird page config, the stack is completely gone:
![image](https://user-images.githubusercontent.com/16538424/179363677-f2eea499-f8ff-47ff-9e24-65a517fb75d5.png)

**Comment by Wierzbowsky** [comment]
I debugged a bit deeper and found who makes a mess. It's the internal "MSXWord" ROM that messes up page configuration so that the stack is gone. So, this is not Nextor's fault. Ticket can be closed.
![image](https://user-images.githubusercontent.com/16538424/179365335-2d7032a6-ff11-40ac-91b6-aab6d616bb0d.png)

**Comment by Konamiman** [comment]
Cool, closing then, thanks for the info.
