### ISSUE TITLE
NEXTOR.SYS not loading from 1st device when Nextor+SunriseIDE is 2nd.

### ISSUE THREAD

**Issue by S0urceror** [Konamiman/Nextor#75]
I recently got a Carnivore2 which I use in combination with my MSXUSB cartridge and software. Both are running the latest Nextor 2.1.0.

When Carnivore2+SunriseIDE is in slot 1 and MSXUSB is in slot 2 all is fine. When MSXUSB is in slot 1 and Carnivore is in slot 2 it hangs after displaying:
```
NEXTOR.SYS version 2.11
Copyright (2019) Konamiman
```
When SunriseIDE is disabled in Carnivore2 it boots normally from MSXUSB in slot 1.

I believe this is not a Nextor issue per se because when I have a RookieDrive in slot 2 and a MSXUSB in slot 1 all is fine. I am suspecting the SunriseIDE to mess up something in DRV_INIT so that the first driver does not boot anymore. When reading the other issues #63 and #64 I'm getting even more convinced buffers are overwritten by the driver messing up the boot sequence.

Will continue to investigate and if I find what it is I'll let you all know.

**Comment by Konamiman** [comment]
This problem also appears when using a MegaFlashROM SCC+SD in a SX|2. The good news is that it will be fixed by https://github.com/Konamiman/Nextor/pull/103
