### ISSUE TITLE
2.1.1 alpha2 file creation bug?

### ISSUE THREAD

**Issue by lintweaker** [Konamiman/Nextor#85]
I have a DOS2 program which loads various files, adds headers and creates one big file with the loaded files including headers.
This is a very old program (from 1994) I wrote and it worked great with DOS2.20/2.31. I also have a program to verify the created file and with the current/latest Nextor version it reports issues with the created file (and it is no longer usable).
I have tried on various real and emulated MSX computers and came to the conclusion that it still works with Nextor 2.1.0 but no longer with the current version. Maybe a bug or behaviour change?

I use the following BDOS calls to create, save and append the file:
_setdta (1ah)
_fmake (16h)
_wrblk (26h)
_fclose (10h)

Let me know if you need more info. It took some head scratching why my programm suddenly stopped working.

**Comment by Konamiman** [comment]
Hi, do you have the source of your program by chance? Or at least can tell with which parameters are these BDOS functions called?

**Comment by lintweaker** [comment]
Hi,
Let me check if I:
- can still reproduce the issue
- if so if I can provide a minimal program which exhibits the issue
(can take a little while)

**Comment by Konamiman** [comment]
Hi, I'm closing this for now, please let me know if you can provide more info and then I'll reopen it.
