### ISSUE TITLE
Register corruption problem when calling memory mapper support extended BIOS

### ISSUE THREAD

**Issue by hra1129** [Konamiman/Nextor#87]
[Issues]
"Calling 'Get mapper variable table' will change the value of the DE register.

[Description]
As the return value, DE is Reserved, so at first glance it looks fine.
However, in MSX-DOS2, the DE register is not destroyed, but is maintained at 0401h.

The MSX Technical Guidebook, which was sold in Japan a long time ago, clearly states that 'Get mapper variable table' "maintains the value of DE".
It is not important that the information in this document is appropriate for the MSX-DOS2 specifications.
In MSX-DOS2, DEs are actually saved. And there is software out there that expects it.

[Appendix]
For example, ”SZMMP (鈴見咲 MIDI Player) ver0.64” will run out of control due to this problem.
http://sakuramail.net/fswold/midi.html

ASCAT Technical Guide Book 
http://www.ascat.jp/tg/tg2.html
　●マッパテーブルの先頭アドレスを得る方法 (How to get the top address of the mapper table)
　　ＤＥは保存される (DE is saved.)

**Comment by Konamiman** [comment]
Fixed in [v2.1.1 beta 1](https://github.com/Konamiman/Nextor/releases/tag/v2.1.1-beta-1).
